os161-doc: os161-base-2.0.2/userland/sbin/sfsck/pass2.c File Reference
pass2.c File Reference
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include <err.h>
#include "compat.h"
#include <kern/sfs.h>
#include "disk.h"
#include "utils.h"
#include "ibmacros.h"
#include "sfs.h"
#include "sb.h"
#include "freemap.h"
#include "inode.h"
#include "passes.h"
#include "main.h"
Functions
static int pass2_dir (uint32_t ino, uint32_t parentino, const char *pathsofar)
void pass2 (void)
Function Documentation
void pass2 (void)
Definition at line 319 of file pass2.c.
References pass2_dir(), sb_volname(), SFS_ROOTDIR_INO, SFS_VOLNAME_SIZE, and snprintf().
Referenced by main().
static int pass2_dir (uint32_t ino, uint32_t parentino, const char * pathsofar) static
Definition at line 63 of file pass2.c.
References assert, bzero(), domalloc(), EXIT_RECOV, EXIT_UNRECOV, free(), inode_addlink(), inode_visitdir(), setbadness(), sfs_direntry::sfd_ino, sfs_direntry::sfd_name, sfs_dinode::sfi_linkcount, sfs_dinode::sfi_size, sfs_dinode::sfi_type, SFS_BLOCKSIZE, SFS_NAMELEN, SFS_NOINO, sfs_readdir(), sfs_readinode(), SFS_ROUNDUP, SFS_TYPE_DIR, SFS_TYPE_FILE, sfs_writedir(), sfs_writeinode(), sfsdir_sort(), sfsdir_tryadd(), snprintf(), strcmp(), strlen(), uniqueid(), and warnx().
Referenced by pass2().