os161-doc: os161-base-2.0.2/userland/testbin/f_test/f_read.c File Reference
f_read.c File Reference
#include <stdio.h>
#include <unistd.h>
#include <err.h>
#include "f_hdr.h"
Macros
#define SectorSize 512
#define TMULT 50
#define FSIZE ((SectorSize + 1) * TMULT)
#define FNAME "f-testfile"
#define READCHAR 'r'
#define WRITECHAR 'w'
Functions
static void check_buffer (void)
void subproc_read (void)
Variables
static char buffer [SectorSize+1]
Macro Definition Documentation
#define FNAME "f-testfile"
Definition at line 49 of file f_read.c.
Referenced by subproc_read().
#define FSIZE ((SectorSize + 1) * TMULT)
Definition at line 47 of file f_read.c.
#define READCHAR 'r'
Definition at line 50 of file f_read.c.
#define SectorSize 512
Definition at line 44 of file f_read.c.
Referenced by check_buffer(), and subproc_read().
#define TMULT 50
Definition at line 46 of file f_read.c.
Referenced by subproc_read().
#define WRITECHAR 'w'
Definition at line 51 of file f_read.c.
Function Documentation
static void check_buffer (void) static
Definition at line 62 of file f_read.c.
References buffer, ch, errx(), putchar(), and SectorSize.
Referenced by subproc_read().
void subproc_read (void)
Definition at line 77 of file f_read.c.
References buffer, check_buffer(), close(), err(), errx(), fd, FNAME, O_RDONLY, open(), printf(), read(), SectorSize, and TMULT.
Referenced by concur().
Variable Documentation
char buffer[SectorSize+1] static
Definition at line 58 of file f_read.c.
Referenced by check_buffer(), and subproc_read().