os161-doc: os161-base-2.0.2/kern/vfs/vfslookup.c File Reference
vfslookup.c File Reference
#include <types.h>
#include <kern/errno.h>
#include <limits.h>
#include <lib.h>
#include <synch.h>
#include <vfs.h>
#include <fs.h>
#include <vnode.h>
Functions
static void change_bootfs (struct vnode *newvn)
int vfs_setbootfs (const char *fsname)
void vfs_clearbootfs (void)
static int getdevice (char *path, char **subpath, struct vnode **startvn)
int vfs_lookparent (char *path, struct vnode **retval, char *buf, size_t buflen)
int vfs_lookup (char *path, struct vnode **retval)
Variables
static struct vnode * bootfs_vnode = NULL
Function Documentation
static void change_bootfs (struct vnode * newvn) static
Definition at line 50 of file vfslookup.c.
References bootfs_vnode, NULL, and VOP_DECREF.
Referenced by vfs_clearbootfs(), and vfs_setbootfs().
static int getdevice (char * path, char ** subpath, struct vnode ** startvn) static
Definition at line 130 of file vfslookup.c.
References bootfs_vnode, ENOENT, FSOP_GETROOT, KASSERT, NULL, vfs_biglock_do_i_hold(), vfs_getcurdir(), vfs_getroot(), vnode::vn_fs, VOP_DECREF, and VOP_INCREF.
Referenced by vfs_lookparent(), and vfs_lookup().
void vfs_clearbootfs (void)
Definition at line 115 of file vfslookup.c.
References change_bootfs(), NULL, vfs_biglock_acquire(), and vfs_biglock_release().
Referenced by shutdown().
int vfs_lookparent (char * path, struct vnode ** retval, char * buf, size_t buflen)
Definition at line 236 of file vfslookup.c.
References EINVAL, getdevice(), strlen(), vfs_biglock_acquire(), vfs_biglock_release(), VOP_DECREF, and VOP_LOOKPARENT.
Referenced by vfs_link(), vfs_mkdir(), vfs_open(), vfs_remove(), vfs_rename(), vfs_rmdir(), and vfs_symlink().
int vfs_lookup (char * path, struct vnode ** retval)
Definition at line 269 of file vfslookup.c.
References getdevice(), strlen(), vfs_biglock_acquire(), vfs_biglock_release(), VOP_DECREF, and VOP_LOOKUP.
Referenced by vfs_chdir(), vfs_link(), vfs_open(), and vfs_readlink().
int vfs_setbootfs (const char * fsname)
Definition at line 71 of file vfslookup.c.
References change_bootfs(), EINVAL, NAME_MAX, snprintf(), strcat(), strchr(), strlen(), vfs_biglock_acquire(), vfs_biglock_release(), vfs_chdir(), and vfs_getcurdir().
Referenced by boot(), and cmd_bootfs().
Variable Documentation
struct vnode* bootfs_vnode = NULL static
Definition at line 43 of file vfslookup.c.
Referenced by change_bootfs(), and getdevice().