os161-doc: os161-base-2.0.2/userland/lib/libc/stdio/putchar.c File Reference
putchar.c File Reference
#include <stdio.h>
#include <unistd.h>
Functions
int putchar (int ch)
Function Documentation
int putchar (int ch)
Definition at line 41 of file putchar.c.
References ch, EOF, STDOUT_FILENO, and write().
Referenced by baseparent(), check_buffer(), concparent(), dumpfileblock(), dumpfreemap(), dumpval(), getcmd(), geti(), main(), pong_cyclic(), pong_reciprocating(), puts(), read_string(), say(), and test().