os161-doc: os161-base-2.0.2/kern/include/proc.h File Reference
proc.h File Reference
#include <spinlock.h>
Data Structures
struct proc
Functions
void proc_bootstrap (void)
struct proc * proc_create_runprogram (const char *name)
void proc_destroy (struct proc *proc)
int proc_addthread (struct proc *proc, struct thread *t)
void proc_remthread (struct thread *t)
struct addrspace * proc_getas (void)
struct addrspace * proc_setas (struct addrspace *)
Variables
struct proc * kproc
Function Documentation
int proc_addthread (struct proc * proc, struct thread * t)
Definition at line 234 of file proc.c.
References KASSERT, NULL, proc::p_lock, proc::p_numthreads, spinlock_acquire(), spinlock_release(), splhigh(), splx(), and thread::t_proc.
Referenced by cpu_create(), and thread_fork().
void proc_bootstrap (void)
Definition at line 179 of file proc.c.
References NULL, panic(), and proc_create().
Referenced by boot().
struct proc* proc_create_runprogram (const char * name)
Definition at line 194 of file proc.c.
References curproc, NULL, proc::p_addrspace, proc::p_cwd, proc_create(), spinlock_acquire(), spinlock_release(), and VOP_INCREF.
Referenced by common_prog().
void proc_destroy (struct proc * proc)
Definition at line 95 of file proc.c.
References as_deactivate(), as_destroy(), curproc, KASSERT, kfree(), NULL, proc::p_addrspace, proc::p_cwd, proc::p_lock, proc::p_name, proc::p_numthreads, proc_setas(), spinlock_cleanup(), and VOP_DECREF.
Referenced by common_prog().
struct addrspace* proc_getas (void)
Definition at line 288 of file proc.c.
References curproc, NULL, proc::p_addrspace, proc::p_lock, spinlock_acquire(), and spinlock_release().
Referenced by as_activate(), load_elf(), runprogram(), uiomove(), and vm_fault().
void proc_remthread (struct thread * t)
Definition at line 261 of file proc.c.
References KASSERT, NULL, proc::p_lock, proc::p_numthreads, spinlock_acquire(), spinlock_release(), splhigh(), splx(), and thread::t_proc.
Referenced by thread_exit().
struct addrspace* proc_setas (struct addrspace *)
Definition at line 308 of file proc.c.
References curproc, KASSERT, NULL, proc::p_addrspace, proc::p_lock, spinlock_acquire(), and spinlock_release().
Referenced by proc_destroy(), and runprogram().
Variable Documentation
struct proc* kproc
Definition at line 55 of file proc.c.
Referenced by cpu_create(), and thread_bootstrap().