os161-doc: os161-base-2.0.2/kern/dev/lamebus/ltimer.c File Reference
ltimer.c File Reference
#include <types.h>
#include <lib.h>
#include <spl.h>
#include <clock.h>
#include <platform/bus.h>
#include <lamebus/ltimer.h>
#include "autoconf.h"
Macros
#define LT_REG_SEC 0 /* time of day: seconds */
#define LT_REG_NSEC 4 /* time of day: nanoseconds */
#define LT_REG_ROE 8 /* Restart On countdown-timer Expiry flag */
#define LT_REG_IRQ 12 /* Interrupt status register */
#define LT_REG_COUNT 16 /* Time for countdown timer (usec) */
#define LT_REG_SPKR 20 /* Beep control */
#define LT_GRANULARITY 1000000
Functions
int config_ltimer (struct ltimer_softc *lt, int ltimerno)
void ltimer_irq (void *vlt)
void ltimer_beep (void *vlt)
void ltimer_gettime (void *vlt, struct timespec *ts)
Variables
static bool havetimerclock
Macro Definition Documentation
#define LT_GRANULARITY 1000000
Definition at line 50 of file ltimer.c.
Referenced by config_ltimer().
#define LT_REG_COUNT 16 /* Time for countdown timer (usec) */
Definition at line 46 of file ltimer.c.
Referenced by config_ltimer().
#define LT_REG_IRQ 12 /* Interrupt status register */
Definition at line 45 of file ltimer.c.
Referenced by ltimer_irq().
#define LT_REG_NSEC 4 /* time of day: nanoseconds */
Definition at line 43 of file ltimer.c.
Referenced by ltimer_gettime().
#define LT_REG_ROE 8 /* Restart On countdown-timer Expiry flag */
Definition at line 44 of file ltimer.c.
Referenced by config_ltimer().
#define LT_REG_SEC 0 /* time of day: seconds */
Definition at line 42 of file ltimer.c.
Referenced by ltimer_gettime().
#define LT_REG_SPKR 20 /* Beep control */
Definition at line 47 of file ltimer.c.
Referenced by ltimer_beep().
Function Documentation
int config_ltimer (struct ltimer_softc * lt, int ltimerno)
Definition at line 58 of file ltimer.c.
References bus_write_register, havetimerclock, ltimer_softc::lt_bus, ltimer_softc::lt_buspos, LT_GRANULARITY, ltimer_softc::lt_hardclock, LT_REG_COUNT, LT_REG_ROE, and ltimer_softc::lt_timerclock.
Referenced by tryattach_ltimer_to_lamebus().
void ltimer_beep (void * vlt)
Definition at line 136 of file ltimer.c.
References bus_write_register, ltimer_softc::lt_bus, ltimer_softc::lt_buspos, and LT_REG_SPKR.
Referenced by attach_beep_to_ltimer().
void ltimer_gettime (void * vlt, struct timespec * ts)
Definition at line 149 of file ltimer.c.
References bus_read_register, ltimer_softc::lt_bus, ltimer_softc::lt_buspos, LT_REG_NSEC, LT_REG_SEC, splhigh(), splx(), timespec::tv_nsec, and timespec::tv_sec.
Referenced by attach_rtclock_to_ltimer().
void ltimer_irq (void * vlt)
Definition at line 107 of file ltimer.c.
References bus_read_register, hardclock(), ltimer_softc::lt_bus, ltimer_softc::lt_buspos, ltimer_softc::lt_hardclock, LT_REG_IRQ, ltimer_softc::lt_timerclock, and timerclock().
Referenced by attach_ltimer_to_lamebus().
Variable Documentation
bool havetimerclock static
Definition at line 52 of file ltimer.c.
Referenced by config_ltimer().