os161-doc: os161-base-2.0.2/userland/testbin/badcall/bad_open.c File Reference
bad_open.c File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <err.h>
#include "config.h"
#include "test.h"
Functions
static void open_badflags (void)
static void open_empty (void)
void test_open (void)
Function Documentation
static void open_badflags (void) static
Definition at line 48 of file bad_open.c.
References EINVAL, errno, fd, open(), report_begin(), and report_check().
Referenced by test_open().
static void open_empty (void) static
Definition at line 59 of file bad_open.c.
References close(), EINVAL, errno, O_RDONLY, open(), report_begin(), and report_check2().
Referenced by test_open().
void test_open (void)
Definition at line 72 of file bad_open.c.
References open_badflags(), open_empty(), and test_open_path().