os161-doc: os161-base-2.0.2/userland/testbin/tictac/tictac.c File Reference
tictac.c File Reference
#include <stdio.h>
#include <unistd.h>
Macros
#define NEWLINE 012
#define EMPTY 0
#define X_PLAYER 1
#define O_PLAYER 2
#define X_MARKER 1
#define O_MARKER 2
#define DIM 3
#define DIMCHAR "2"
#define MAXSTRING 100
Enumerations
enum bool { FALSE, TRUE }
Functions
bool ask_yesno (const char *msg)
bool do_move (int player)
void initialize_board (void)
bool is_win (int x, int y)
int read_string (char *buf, int length)
void print_board (void)
void print_instructions (void)
bool win_column (int y, int marker)
bool win_diag_left (int x, int y, int marker)
bool win_diag_right (int x, int y, int marker)
bool win_row (int x, int marker)
bool Strcmp (const char *a, const char *b)
int main (void)
Variables
int board [DIM][DIM]
Macro Definition Documentation
#define DIM 3
Definition at line 50 of file tictac.c.
Referenced by do_move(), initialize_board(), main(), print_board(), win_column(), win_diag_left(), win_diag_right(), and win_row().
#define DIMCHAR "2"
Definition at line 51 of file tictac.c.
#define EMPTY 0
Definition at line 45 of file tictac.c.
Referenced by do_move(), initialize_board(), and print_board().
#define MAXSTRING 100
Definition at line 52 of file tictac.c.
Referenced by ask_yesno(), and do_move().
#define NEWLINE 012
Definition at line 44 of file tictac.c.
Referenced by read_string().
#define O_MARKER 2
Definition at line 49 of file tictac.c.
Referenced by do_move(), and print_board().
#define O_PLAYER 2
Definition at line 47 of file tictac.c.
#define X_MARKER 1
Definition at line 48 of file tictac.c.
Referenced by do_move(), and print_board().
#define X_PLAYER 1
Definition at line 46 of file tictac.c.
Referenced by do_move().
Enumeration Type Documentation
enum bool
Enumerator
FALSE
TRUE
Definition at line 54 of file tictac.c.
Function Documentation
bool ask_yesno (const char * msg)
Definition at line 179 of file tictac.c.
References answer(), FALSE, MAXSTRING, printf(), read_string(), Strcmp(), and TRUE.
Referenced by main().
bool do_move (int player)
Definition at line 213 of file tictac.c.
References answer(), board, DIM, EMPTY, FALSE, is_win(), MAXSTRING, O_MARKER, print_board(), printf(), read_string(), TRUE, X_MARKER, and X_PLAYER.
Referenced by main().
void initialize_board (void)
Definition at line 347 of file tictac.c.
References board, DIM, and EMPTY.
Referenced by main().
bool is_win (int x, int y)
Definition at line 278 of file tictac.c.
References board, win_column(), win_diag_left(), win_diag_right(), and win_row().
Referenced by do_move().
int main (void)
Definition at line 79 of file tictac.c.
References ask_yesno(), DIM, do_move(), FALSE, initialize_board(), print_board(), print_instructions(), printf(), and TRUE.
void print_board (void)
Definition at line 140 of file tictac.c.
References board, DIM, EMPTY, O_MARKER, printf(), and X_MARKER.
Referenced by do_move(), and main().
void print_instructions (void)
Definition at line 122 of file tictac.c.
References printf().
Referenced by main().
int read_string (char * buf, int length)
Definition at line 357 of file tictac.c.
References EOF, getchar(), NEWLINE, and putchar().
Referenced by ask_yesno(), and do_move().
bool Strcmp (const char * a, const char * b)
Definition at line 384 of file tictac.c.
References FALSE, and NULL.
Referenced by ask_yesno().
bool win_column (int y, int marker)
Definition at line 298 of file tictac.c.
References board, DIM, FALSE, and TRUE.
Referenced by is_win().
bool win_diag_left (int x, int y, int marker)
Definition at line 318 of file tictac.c.
References board, DIM, FALSE, and TRUE.
Referenced by is_win().
bool win_diag_right (int x, int y, int marker)
Definition at line 333 of file tictac.c.
References board, DIM, FALSE, and TRUE.
Referenced by is_win().
bool win_row (int x, int marker)
Definition at line 308 of file tictac.c.
References board, DIM, FALSE, and TRUE.
Referenced by is_win().
Variable Documentation
int board[DIM][DIM]
Definition at line 74 of file tictac.c.
Referenced by do_move(), initialize_board(), is_win(), print_board(), win_column(), win_diag_left(), win_diag_right(), and win_row().