os161-doc: os161-base-2.0.2/kern/dev/lamebus/emu.h File Reference
emu.h File Reference
Data Structures
struct emu_softc
Macros
#define EMU_MAXIO 16384
#define EMU_ROOTHANDLE 0
Functions
void emu_irq (void *)
Macro Definition Documentation
#define EMU_MAXIO 16384
Definition at line 34 of file emu.h.
Referenced by emu_open(), emufs_getdirentry(), emufs_read(), and emufs_write().
#define EMU_ROOTHANDLE 0
Definition at line 35 of file emu.h.
Referenced by emufs_addtovfs().
Function Documentation
void emu_irq (void *)
Definition at line 125 of file emu.c.
References emu_softc::e_result, emu_softc::e_sem, emu_rreg(), emu_wreg(), REG_RESULT, and V().
Referenced by attach_emu_to_lamebus().