os161-doc: os161-base-2.0.2/userland/lib/libtest/triple.c File Reference
triple.c File Reference
#include <stdio.h>
#include <unistd.h>
#include <err.h>
#include <test/triple.h>
Functions
static pid_t spawnv (const char *prog, char **argv)
static int dowait (int index, int pid)
void triple (const char *prog)
Function Documentation
static int dowait (int index, int pid) static
Definition at line 62 of file triple.c.
References waitpid(), warn(), warnx(), WEXITSTATUS, WIFSIGNALED, and WTERMSIG.
Referenced by triple().
static pid_t spawnv (const char * prog, char ** argv) static
Definition at line 43 of file triple.c.
References err(), execv(), fork(), and pid.
Referenced by triple().
void triple (const char * prog)
Definition at line 84 of file triple.c.
References dowait(), failures, NULL, pids, spawnv(), and warnx().
Referenced by main().