os161-doc: os161-base-2.0.2/kern/dev/lamebus/ltrace_att.c File Reference
ltrace_att.c File Reference
#include <types.h>
#include <lib.h>
#include <lamebus/lamebus.h>
#include <lamebus/ltrace.h>
#include "autoconf.h"
Macros
#define LOW_VERSION 1
#define STOP_VERSION 2
#define PROF_VERSION 3
Functions
struct ltrace_softc * attach_ltrace_to_lamebus (int ltraceno, struct lamebus_softc *sc)
Macro Definition Documentation
#define LOW_VERSION 1
Definition at line 37 of file ltrace_att.c.
Referenced by attach_ltrace_to_lamebus().
#define PROF_VERSION 3
Definition at line 41 of file ltrace_att.c.
Referenced by attach_ltrace_to_lamebus().
#define STOP_VERSION 2
Definition at line 39 of file ltrace_att.c.
Referenced by attach_ltrace_to_lamebus().
Function Documentation
struct ltrace_softc* attach_ltrace_to_lamebus (int ltraceno, struct lamebus_softc * sc)
Definition at line 44 of file ltrace_att.c.
References kmalloc(), lamebus_mark(), lamebus_probe(), LB_VENDOR_CS161, LBCS161_TRACE, LOW_VERSION, ltrace_softc::lt_busdata, ltrace_softc::lt_buspos, ltrace_softc::lt_canprof, ltrace_softc::lt_canstop, NULL, PROF_VERSION, and STOP_VERSION.
Referenced by tryattach_ltrace_to_lamebus().