os161-doc: os161-base-2.0.2/kern/test/threadtest.c File Reference
threadtest.c File Reference
#include <types.h>
#include <lib.h>
#include <thread.h>
#include <synch.h>
#include <test.h>
Macros
#define NTHREADS 8
Functions
static void init_sem (void)
static void loudthread (void *junk, unsigned long num)
static void quietthread (void *junk, unsigned long num)
static void runthreads (int doloud)
int threadtest (int nargs, char **args)
int threadtest2 (int nargs, char **args)
Variables
static struct semaphore * tsem = NULL
Macro Definition Documentation
#define NTHREADS 8
Definition at line 39 of file threadtest.c.
Referenced by runthreads().
Function Documentation
static void init_sem (void) static
Definition at line 45 of file threadtest.c.
References NULL, panic(), and sem_create().
Referenced by threadtest(), and threadtest2().
static void loudthread (void * junk, unsigned long num) static
Definition at line 57 of file threadtest.c.
References ch, num, putch(), and V().
Referenced by runthreads().
static void quietthread (void * junk, unsigned long num) static
Definition at line 82 of file threadtest.c.
References ch, num, putch(), and V().
Referenced by runthreads().
static void runthreads (int doloud) static
Definition at line 98 of file threadtest.c.
References loudthread(), name, NTHREADS, NULL, P(), panic(), quietthread(), snprintf(), strerror(), and thread_fork().
Referenced by threadtest(), and threadtest2().
int threadtest (int nargs, char ** args)
Definition at line 121 of file threadtest.c.
References init_sem(), kprintf(), and runthreads().
int threadtest2 (int nargs, char ** args)
Definition at line 135 of file threadtest.c.
References init_sem(), kprintf(), and runthreads().
Variable Documentation
struct semaphore* tsem = NULL static
Definition at line 41 of file threadtest.c.