os161-doc: os161-base-2.0.2/kern/lib/bitmap.c File Reference
bitmap.c File Reference
#include <types.h>
#include <kern/errno.h>
#include <lib.h>
#include <bitmap.h>
Data Structures
struct bitmap
Macros
#define BITS_PER_WORD (CHAR_BIT)
#define WORD_TYPE unsigned char
#define WORD_ALLBITS (0xff)
Functions
struct bitmap * bitmap_create (unsigned nbits)
void * bitmap_getdata (struct bitmap *b)
int bitmap_alloc (struct bitmap *b, unsigned *index)
static void bitmap_translate (unsigned bitno, unsigned *ix, WORD_TYPE *mask)
void bitmap_mark (struct bitmap *b, unsigned index)
void bitmap_unmark (struct bitmap *b, unsigned index)
int bitmap_isset (struct bitmap *b, unsigned index)
void bitmap_destroy (struct bitmap *b)
Macro Definition Documentation
#define BITS_PER_WORD (CHAR_BIT)
Definition at line 46 of file bitmap.c.
Referenced by bitmap_alloc(), bitmap_create(), and bitmap_translate().
#define WORD_ALLBITS (0xff)
Definition at line 48 of file bitmap.c.
Referenced by bitmap_alloc().
#define WORD_TYPE unsigned char
Definition at line 47 of file bitmap.c.
Referenced by bitmap_alloc(), bitmap_create(), bitmap_isset(), bitmap_mark(), bitmap_translate(), and bitmap_unmark().
Function Documentation
int bitmap_alloc (struct bitmap * b, unsigned * index)
Definition at line 99 of file bitmap.c.
References BITS_PER_WORD, DIVROUNDUP, ENOSPC, KASSERT, bitmap::nbits, bitmap::v, WORD_ALLBITS, and WORD_TYPE.
Referenced by bitmaptest(), and sfs_balloc().
struct bitmap* bitmap_create (unsigned nbits)
Definition at line 57 of file bitmap.c.
References BITS_PER_WORD, bzero(), DIVROUNDUP, KASSERT, kfree(), kmalloc(), bitmap::nbits, NULL, bitmap::v, and WORD_TYPE.
Referenced by bitmaptest(), and sfs_domount().
void bitmap_destroy (struct bitmap * b)
Definition at line 172 of file bitmap.c.
References kfree(), and bitmap::v.
Referenced by sfs_fs_destroy().
void* bitmap_getdata (struct bitmap * b)
Definition at line 93 of file bitmap.c.
References bitmap::v.
Referenced by sfs_freemapio().
int bitmap_isset (struct bitmap * b, unsigned index)
Definition at line 162 of file bitmap.c.
References bitmap_translate(), bitmap::v, and WORD_TYPE.
Referenced by bitmaptest(), and sfs_bused().
void bitmap_mark (struct bitmap * b, unsigned index)
Definition at line 135 of file bitmap.c.
References bitmap_translate(), KASSERT, bitmap::nbits, bitmap::v, and WORD_TYPE.
Referenced by bitmaptest().
static void bitmap_translate (unsigned bitno, unsigned * ix, WORD_TYPE * mask) inline static
Definition at line 126 of file bitmap.c.
References BITS_PER_WORD, and WORD_TYPE.
Referenced by bitmap_isset(), bitmap_mark(), and bitmap_unmark().
void bitmap_unmark (struct bitmap * b, unsigned index)
Definition at line 148 of file bitmap.c.
References bitmap_translate(), KASSERT, bitmap::nbits, bitmap::v, and WORD_TYPE.
Referenced by bitmaptest(), sfs_balloc(), and sfs_bfree().