os161-doc: os161-base-2.0.2/userland/testbin/schedpong/results.h File Reference
results.h File Reference
Functions
void createresultsfile (void)
void destroyresultsfile (void)
void openresultsfile (int openflags)
void closeresultsfile (void)
void putresult (unsigned groupid, time_t secs, unsigned long nsecs)
void getresult (unsigned groupid, time_t *secs, unsigned long *nsecs)
Function Documentation
void closeresultsfile (void)
Definition at line 99 of file results.c.
References assert, close(), RESULTSFILE, resultsfile, and warn().
Referenced by runit(), and runtaskgroup().
void createresultsfile (void)
Definition at line 48 of file results.c.
References assert, close(), err(), fd, O_CREAT, O_RDWR, O_TRUNC, open(), RESULTSFILE, resultsfile, and warn().
Referenced by runit().
void destroyresultsfile (void)
Definition at line 68 of file results.c.
References ENOSYS, errno, RESULTSFILE, and warn().
Referenced by runit().
void getresult (unsigned groupid, time_t * secs, unsigned long * nsecs)
Definition at line 144 of file results.c.
References assert, err(), errx(), lseek(), pos, read(), RESULTSFILE, resultsfile, and SEEK_SET.
Referenced by calcresult().
void openresultsfile (int openflags)
Definition at line 84 of file results.c.
References assert, err(), O_RDONLY, O_WRONLY, open(), RESULTSFILE, and resultsfile.
Referenced by runit(), and runtaskgroup().
void putresult (unsigned groupid, time_t secs, unsigned long nsecs)
Definition at line 113 of file results.c.
References assert, err(), errx(), lseek(), pos, RESULTSFILE, resultsfile, SEEK_SET, and write().
Referenced by runtaskgroup().