os161-doc: os161-base-2.0.2/userland/testbin/f_test/f_test.c File Reference
f_test.c File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <err.h>
#include "f_hdr.h"
Macros
#define SECTOR_SIZE 512
#define BUFFER_SIZE (2 * SECTOR_SIZE + 1)
#define BIGFILE_SIZE (270 * BUFFER_SIZE)
#define BIGFILE_NAME "large-f"
#define LETTER(x) ('a' + (x % 31))
#define DIR_DEPTH 8
#define DIR_NAME "/t"
#define DIRFILE_NAME "a"
#define FNAME "f-testfile"
#define TMULT 50
#define FSIZE ((SECTOR_SIZE + 1) * TMULT)
#define READCHAR 'r'
#define WRITECHAR 'w'
#define RUNBIGFILE 0x1
#define RUNDIRTEST 0x2
#define RUNCONCUR 0x4
#define RUNTHEMALL (RUNBIGFILE | RUNDIRTEST | RUNCONCUR)
Functions
static pid_t forkoff (void(*func)(void))
static void dowait (int pid)
static void big_file (int size)
static void concur (void)
static void dir_test (int depth)
int main (int argc, char *argv[])
Variables
char fbuffer [BUFFER_SIZE]
char ibuffer [32]
char cbuffer [SECTOR_SIZE+1]
Macro Definition Documentation
#define BIGFILE_NAME "large-f"
Definition at line 56 of file f_test.c.
Referenced by big_file().
#define BIGFILE_SIZE (270 * BUFFER_SIZE)
Definition at line 55 of file f_test.c.
Referenced by main().
#define BUFFER_SIZE (2 * SECTOR_SIZE + 1)
Definition at line 54 of file f_test.c.
Referenced by big_file().
#define DIR_DEPTH 8
Definition at line 64 of file f_test.c.
Referenced by main().
#define DIR_NAME "/t"
Definition at line 65 of file f_test.c.
Referenced by dir_test().
#define DIRFILE_NAME "a"
Definition at line 66 of file f_test.c.
Referenced by dir_test().
#define FNAME "f-testfile"
Definition at line 69 of file f_test.c.
Referenced by concur().
#define FSIZE ((SECTOR_SIZE + 1) * TMULT)
Definition at line 71 of file f_test.c.
#define LETTER (x) ('a' + (x % 31))
Definition at line 58 of file f_test.c.
Referenced by big_file().
#define READCHAR 'r'
Definition at line 73 of file f_test.c.
Referenced by concur().
#define RUNBIGFILE 0x1
Definition at line 302 of file f_test.c.
Referenced by main().
#define RUNCONCUR 0x4
Definition at line 304 of file f_test.c.
Referenced by main().
#define RUNDIRTEST 0x2
Definition at line 303 of file f_test.c.
Referenced by main().
#define RUNTHEMALL (RUNBIGFILE | RUNDIRTEST | RUNCONCUR)
Definition at line 305 of file f_test.c.
Referenced by main().
#define SECTOR_SIZE 512
Definition at line 51 of file f_test.c.
Referenced by concur().
#define TMULT 50
Definition at line 70 of file f_test.c.
Referenced by concur().
#define WRITECHAR 'w'
Definition at line 74 of file f_test.c.
Function Documentation
static void big_file (int size) static
Definition at line 123 of file f_test.c.
References BIGFILE_NAME, BUFFER_SIZE, close(), err(), errx(), fbuffer, LETTER, O_CREAT, O_RDONLY, O_TRUNC, O_WRONLY, open(), printf(), read(), and write().
Referenced by main().
static void concur (void) static
Definition at line 193 of file f_test.c.
References cbuffer, close(), dowait(), err(), fd, FNAME, forkoff(), O_CREAT, O_TRUNC, O_WRONLY, open(), printf(), READCHAR, SECTOR_SIZE, subproc_read(), subproc_write(), TMULT, and write().
Referenced by main().
static void dir_test (int depth) static
Definition at line 244 of file f_test.c.
References DIR_NAME, DIRFILE_NAME, err(), fd, mkdir(), O_CREAT, O_TRUNC, O_WRONLY, open(), printf(), rmdir(), strcat(), strcpy(), and strlen().
Referenced by main().
static void dowait (int pid) static
Definition at line 102 of file f_test.c.
References waitpid(), warn(), warnx(), WEXITSTATUS, WIFSIGNALED, and WTERMSIG.
Referenced by concur().
static pid_t forkoff (void(*)(void) func) static
Definition at line 85 of file f_test.c.
References _exit(), fork(), pid, and warn().
Referenced by concur().
int main (int argc, char * argv[])
Definition at line 308 of file f_test.c.
References big_file(), BIGFILE_SIZE, concur(), DIR_DEPTH, dir_test(), printf(), RUNBIGFILE, RUNCONCUR, RUNDIRTEST, and RUNTHEMALL.
Variable Documentation
char cbuffer[SECTOR_SIZE+1]
Definition at line 76 of file f_test.c.
Referenced by concur().
char fbuffer[BUFFER_SIZE]
Definition at line 60 of file f_test.c.
Referenced by big_file().
char ibuffer[32]
Definition at line 61 of file f_test.c.