os161-doc: os161-base-2.0.2/userland/testbin/frack/data.h File Reference
data.h File Reference
Macros
#define DATA_MAXSIZE 65536
#define POISON_VAL 0xa9
Functions
void * data_map (unsigned code, unsigned seq, off_t len)
void * data_mapreadbuf (off_t len)
int data_matches (const char *namestr, off_t regionoffset, unsigned code, unsigned seq, off_t zerostart, off_t len, off_t checkstart, off_t checklen)
void data_check (const char *namestr, off_t regionoffset, unsigned code, unsigned seq, off_t zerostart, off_t len, off_t checkstart, off_t checklen)
Macro Definition Documentation
#define DATA_MAXSIZE 65536
Definition at line 40 of file data.h.
Referenced by data_map(), data_mapreadbuf(), data_matches(), and op_write().
#define POISON_VAL 0xa9
Definition at line 41 of file data.h.
Referenced by checkfilezeros(), and poison_at().
Function Documentation
void data_check (const char * namestr, off_t regionoffset, unsigned code, unsigned seq, off_t zerostart, off_t len, off_t checkstart, off_t checklen)
Definition at line 199 of file data.c.
References assert, data_matches(), and printf().
Referenced by checkfiledata().
void* data_map (unsigned code, unsigned seq, off_t len)
Definition at line 215 of file data.c.
References assert, DATA_MAXSIZE, databuf, and prepdata().
Referenced by do_write().
void* data_mapreadbuf (off_t len)
Definition at line 223 of file data.c.
References assert, DATA_MAXSIZE, and readbuf.
Referenced by readfiledata().
int data_matches (const char * namestr, off_t regionoffset, unsigned code, unsigned seq, off_t zerostart, off_t len, off_t checkstart, off_t checklen)
Definition at line 123 of file data.c.
References assert, BLOCKSIZE, DATA_MAXSIZE, databuf, matches_at(), poison_at(), prepdata(), printf(), and zero_at().
Referenced by change_is_present(), and data_check().