os161-doc: os161-base-2.0.2/kern/dev/lamebus/emu_att.c File Reference
emu_att.c File Reference
#include <types.h>
#include <lib.h>
#include <lamebus/lamebus.h>
#include <lamebus/emu.h>
#include "autoconf.h"
Macros
#define LOW_VERSION 1
Functions
struct emu_softc * attach_emu_to_lamebus (int emuno, struct lamebus_softc *sc)
Macro Definition Documentation
#define LOW_VERSION 1
Definition at line 41 of file emu_att.c.
Referenced by attach_emu_to_lamebus().
Function Documentation
struct emu_softc* attach_emu_to_lamebus (int emuno, struct lamebus_softc * sc)
Definition at line 44 of file emu_att.c.
References emu_softc::e_busdata, emu_softc::e_buspos, emu_softc::e_unit, emu_irq(), kmalloc(), lamebus_attach_interrupt(), lamebus_mark(), lamebus_probe(), LB_VENDOR_CS161, LBCS161_EMUFS, LOW_VERSION, and NULL.
Referenced by tryattach_emu_to_lamebus().