os161-doc: os161-base-2.0.2/userland/sbin/sfsck/sb.c File Reference
sb.c File Reference
#include <sys/types.h>
#include <limits.h>
#include <stdint.h>
#include <assert.h>
#include <err.h>
#include "compat.h"
#include <kern/sfs.h>
#include "utils.h"
#include "sfs.h"
#include "sb.h"
#include "freemap.h"
#include "main.h"
Functions
void sb_load (void)
void sb_check (void)
uint32_t sb_totalblocks (void)
uint32_t sb_freemapblocks (void)
const char * sb_volname (void)
Variables
static struct sfs_superblock sb
Function Documentation
void sb_check (void)
Definition at line 66 of file sb.c.
References checkbadstring(), checknullstring(), checkzeroed(), EXIT_RECOV, sfs_superblock::reserved, sb, sfs_superblock::sb_volname, setbadness(), SFS_SUPER_BLOCK, sfs_writesb(), and warnx().
Referenced by main().
uint32_t sb_freemapblocks (void)
Definition at line 112 of file sb.c.
References sb, sfs_superblock::sb_nblocks, and SFS_FREEMAPBLOCKS.
Referenced by freemap_check(), and freemap_setup().
void sb_load (void)
Definition at line 51 of file sb.c.
References assert, errx(), EXIT_FATAL, sb, sfs_superblock::sb_magic, sfs_superblock::sb_nblocks, SFS_FREEMAPBLOCKS, SFS_MAGIC, sfs_readsb(), and SFS_SUPER_BLOCK.
Referenced by main().
uint32_t sb_totalblocks (void)
Definition at line 102 of file sb.c.
References sb, and sfs_superblock::sb_nblocks.
Referenced by check_inode_blocks(), freemap_setup(), main(), and pass1_direntry().
const char* sb_volname (void)
Definition at line 121 of file sb.c.
References sb, and sfs_superblock::sb_volname.
Referenced by pass1_rootdir(), and pass2().
Variable Documentation
struct sfs_superblock sb static
Definition at line 45 of file sb.c.
Referenced by sb_check(), sb_freemapblocks(), sb_load(), sb_totalblocks(), and sb_volname().