os161-doc: os161-base-2.0.2/kern/include/lib.h File Reference
lib.h File Reference
#include <cdefs.h>
#include "opt-noasserts.h"
Macros
#define KASSERT(expr) ((expr) ? (void)0 : badassert(#expr, __FILE__, __LINE__, __func__))
#define DEBUGASSERT(expr) ((void)(expr))
#define DB_LOCORE 0x0001
#define DB_SYSCALL 0x0002
#define DB_INTERRUPT 0x0004
#define DB_DEVICE 0x0008
#define DB_THREADS 0x0010
#define DB_VM 0x0020
#define DB_EXEC 0x0040
#define DB_VFS 0x0080
#define DB_SEMFS 0x0100
#define DB_SFS 0x0200
#define DB_NET 0x0400
#define DB_NETFS 0x0800
#define DB_KMALLOC 0x1000
#define DEBUG(d,...) ((dbflags & (d)) ? kprintf(__VA_ARGS__) : 0)
#define RANDOM_MAX (randmax())
#define DIVROUNDUP(a, b) (((a)+(b)-1)/(b))
#define ROUNDUP(a, b) (DIVROUNDUP(a,b)*b)
Functions
uint32_t randmax (void)
uint32_t random (void)
void * kmalloc (size_t size)
void kfree (void *ptr)
void kheap_printstats (void)
void kheap_nextgeneration (void)
void kheap_dump (void)
void kheap_dumpall (void)
size_t strlen (const char *str)
int strcmp (const char *str1, const char *str2)
char * strcpy (char *dest, const char *src)
char * strcat (char *dest, const char *src)
char * kstrdup (const char *str)
char * strchr (const char *searched, int searchfor)
char * strrchr (const char *searched, int searchfor)
char * strtok_r (char *buf, const char *seps, char **context)
void * memcpy (void *dest, const void *src, size_t len)
void * memmove (void *dest, const void *src, size_t len)
void * memset (void *block, int ch, size_t len)
void bzero (void *ptr, size_t len)
int atoi (const char *str)
int snprintf (char *buf, size_t maxlen, const char *fmt,...) __PF(3
int const char * strerror (int errcode)
void putch (int ch)
int getch (void)
void beep (void)
int kprintf (const char *format,...) __PF(1
int __DEAD void panic (const char *format,...) __PF(1
int __DEAD void __DEAD void badassert (const char *expr, const char *file, int line, const char *func)
void kgets (char *buf, size_t maxbuflen)
void kprintf_bootstrap (void)
Variables
uint32_t dbflags
Macro Definition Documentation
#define DB_DEVICE 0x0008
Definition at line 82 of file lib.h.
#define DB_EXEC 0x0040
Definition at line 85 of file lib.h.
Referenced by load_segment().
#define DB_INTERRUPT 0x0004
Definition at line 81 of file lib.h.
#define DB_KMALLOC 0x1000
Definition at line 91 of file lib.h.
#define DB_LOCORE 0x0001
Definition at line 79 of file lib.h.
#define DB_NET 0x0400
Definition at line 89 of file lib.h.
#define DB_NETFS 0x0800
Definition at line 90 of file lib.h.
#define DB_SEMFS 0x0100
Definition at line 87 of file lib.h.
Referenced by semfs_read(), and semfs_write().
#define DB_SFS 0x0200
Definition at line 88 of file lib.h.
Referenced by sfs_rwblock().
#define DB_SYSCALL 0x0002
Definition at line 80 of file lib.h.
Referenced by mips_trap().
#define DB_THREADS 0x0010
Definition at line 83 of file lib.h.
Referenced by thread_consider_migration().
#define DB_VFS 0x0080
Definition at line 86 of file lib.h.
#define DB_VM 0x0020
Definition at line 84 of file lib.h.
Referenced by vm_fault().
#define DEBUG (d, ...) ((dbflags & (d)) ? kprintf(__VA_ARGS__) : 0)
Definition at line 111 of file lib.h.
Referenced by load_segment(), mips_trap(), semfs_read(), semfs_write(), sfs_rwblock(), thread_consider_migration(), and vm_fault().
#define DEBUGASSERT (expr) ((void)(expr))
Definition at line 70 of file lib.h.
Referenced by thread_create(), thread_switch(), threadlist_addhead(), threadlist_addtail(), threadlist_cleanup(), threadlist_init(), threadlist_insertafternode(), threadlist_insertbeforenode(), threadlist_isempty(), threadlist_remhead(), threadlist_remove(), threadlist_removenode(), threadlist_remtail(), threadlistnode_cleanup(), and threadlistnode_init().
#define DIVROUNDUP (a, b) (((a)+(b)-1)/(b))
Definition at line 194 of file lib.h.
Referenced by bitmap_alloc(), bitmap_create(), kmalloctest3(), sfs_itrunc(), and thread_consider_migration().
#define KASSERT (expr) ((expr) ? (void)0 : badassert(#expr, __FILE__, __LINE__, __func__))
Definition at line 65 of file lib.h.
Referenced by allocpageref(), allocpagerefpage(), arraytest(), arraytest2(), as_copy(), as_define_stack(), as_prepare_load(), badnames(), bitmap_alloc(), bitmap_create(), bitmap_mark(), bitmap_unmark(), bitmaptest(), boot(), check_order(), cmd_dispatch(), cmd_progthread(), compute_thread(), con_io(), config_beep(), config_con(), config_random(), config_rtclock(), cpu_hatch(), cpu_machdep_init(), cv_destroy(), dev_read(), dev_uncreate_vnode(), dev_write(), do_semu1011(), do_semu89(), dumbvm_can_sleep(), emu_doread(), emu_trunc(), emu_write(), emufs_addtovfs(), emufs_getdirentry(), emufs_getroot(), emufs_read(), emufs_reclaim(), emufs_write(), exorcise(), fakethread_destroy(), findmount(), freepageref(), fstest_makename(), fstest_write(), getch(), getdevice(), gettime(), ipi_send(), kfree(), kill_curthread(), kmalloc(), kmalloctest3(), kprintf_bootstrap(), lamebus_attach_interrupt(), lamebus_detach_interrupt(), lamebus_interrupt(), lamebus_map_area(), lamebus_mark(), lamebus_mask_interrupt(), lamebus_unmark(), lamebus_unmask_interrupt(), lock_destroy(), lser_poll_until_write(), mainbus_bootstrap(), mainbus_interrupt(), mips_trap(), mips_usermode(), P(), proc_addthread(), proc_destroy(), proc_remthread(), proc_setas(), putch_delayed(), remove_lists(), rotate(), runprogram(), sem_destroy(), semfs_getdirentry(), semfs_getvnode(), semfs_reclaim(), semfs_remove(), semfs_sem_insert(), semfs_vnode_create(), semu1(), semu1213(), semu14(), semu17(), semu17_sub(), semu18(), semu19(), semu4(), semu5(), sfs_blockio(), sfs_bmap(), sfs_dir_findname(), sfs_dir_nentries(), sfs_fs_destroy(), sfs_io(), sfs_itrunc(), sfs_link(), sfs_loadvnode(), sfs_metaio(), sfs_namefile(), sfs_partialio(), sfs_read(), sfs_readblock(), sfs_reclaim(), sfs_remove(), sfs_rename(), sfs_rwblock(), sfs_unmount(), sfs_write(), sfs_writeblock(), sfs_writedir(), spinlock_cleanup(), spinlock_release(), spllower(), splraise(), subpage_kfree(), subpage_kmalloc(), subpage_stats(), syscall(), testa(), thread_bootstrap(), thread_checkstack(), thread_consider_migration(), thread_destroy(), thread_exit(), thread_machdep_cleanup(), thread_make_runnable(), threadlist_cleanup(), threadlistnode_cleanup(), threadlistnode_init(), threadlisttest_a(), threadlisttest_b(), threadlisttest_c(), threadlisttest_d(), threadlisttest_e(), threadlisttest_f(), uiomove(), uiomovezeros(), V(), vfs_biglock_release(), vfs_getcwd(), vfs_getdevname(), vfs_getroot(), vfs_mount(), vfs_open(), vfs_swapoff(), vfs_swapon(), vfs_unmount(), vm_fault(), vnode_cleanup(), vnode_decref(), vnode_incref(), vnode_init(), waiter(), wchan_isempty(), wchan_sleep(), wchan_wakeall(), and wchan_wakeone().
#define RANDOM_MAX (randmax())
Definition at line 118 of file lib.h.
#define ROUNDUP (a, b) (DIVROUNDUP(a,b)*b)
Definition at line 195 of file lib.h.
Function Documentation
int atoi (const char * str)
Definition at line 50 of file atoi.c.
int __DEAD void __DEAD void badassert (const char * expr, const char * file, int line, const char * func)
Definition at line 212 of file kprintf.c.
References panic().
void beep (void)
Definition at line 63 of file beep.c.
References beep_softc::bs_beep, beep_softc::bs_devdata, kprintf(), and NULL.
Referenced by kgets().
void bzero (void * ptr, size_t len)
Definition at line 49 of file bzero.c.
int getch (void)
Definition at line 219 of file console.c.
References getch_intr(), KASSERT, NULL, and the_console.
Referenced by con_io(), and kgets().
void kfree (void * ptr)
Definition at line 1208 of file kmalloc.c.
References free_kpages(), KASSERT, NULL, PAGE_SIZE, and subpage_kfree().
Referenced by array_cleanup(), array_destroy(), array_preallocate(), as_destroy(), attach_console_to_vfs(), bitmap_create(), bitmap_destroy(), compute_thread(), cv_create(), cv_destroy(), dev_uncreate_vnode(), emufs_addtovfs(), emufs_loadvnode(), emufs_reclaim(), fakethread_destroy(), kmalloctest3(), kmalloctest4thread(), kmallocthread(), lock_create(), lock_destroy(), proc_create(), proc_destroy(), sem_create(), sem_destroy(), semfs_create(), semfs_destroy(), semfs_direntry_create(), semfs_direntry_destroy(), semfs_sem_create(), semfs_sem_destroy(), semfs_vnode_destroy(), sfs_fs_create(), sfs_fs_destroy(), sfs_loadvnode(), sfs_reclaim(), thread_create(), thread_destroy(), vfs_doadd(), vfs_swapon(), and wchan_destroy().
void kgets (char * buf, size_t maxbuflen)
Definition at line 54 of file kgets.c.
References backsp(), beep(), ch, getch(), kprintf(), pos, and putch().
Referenced by menu().
void kheap_dump (void)
Definition at line 711 of file kmalloc.c.
References kprintf(), spinlock_acquire(), and spinlock_release().
Referenced by cmd_kheapdump().
void kheap_dumpall (void)
Definition at line 724 of file kmalloc.c.
References kprintf(), spinlock_acquire(), and spinlock_release().
Referenced by cmd_kheapdump().
void kheap_nextgeneration (void)
Definition at line 701 of file kmalloc.c.
References spinlock_acquire(), and spinlock_release().
Referenced by boot(), and cmd_kheapgeneration().
void kheap_printstats (void)
Definition at line 801 of file kmalloc.c.
References kprintf(), pageref::next_all, NULL, spinlock_acquire(), spinlock_release(), and subpage_stats().
Referenced by cmd_kheapstats().
void* kmalloc (size_t size)
Definition at line 1166 of file kmalloc.c.
References alloc_kpages(), GUARD_OVERHEAD, KASSERT, LABEL_OVERHEAD, NULL, PAGE_SIZE, and subpage_kmalloc().
Referenced by array_create(), array_preallocate(), as_create(), attach_beep_to_ltimer(), attach_con_to_lscreen(), attach_con_to_lser(), attach_console_to_vfs(), attach_emu_to_lamebus(), attach_lhd_to_lamebus(), attach_lrandom_to_lamebus(), attach_lscreen_to_lamebus(), attach_lser_to_lamebus(), attach_ltimer_to_lamebus(), attach_ltrace_to_lamebus(), attach_random_to_lrandom(), attach_rtclock_to_ltimer(), bitmap_create(), compute_thread(), cpu_create(), cv_create(), dev_create_vnode(), devnull_create(), emufs_addtovfs(), emufs_loadvnode(), fakethread_create(), kmalloctest3(), kmalloctest4thread(), kmallocthread(), kstrdup(), lamebus_init(), lock_create(), mkrawname(), proc_create(), sem_create(), semfs_create(), semfs_direntry_create(), semfs_sem_create(), semfs_vnode_create(), sfs_fs_create(), sfs_loadvnode(), thread_create(), thread_fork(), vfs_doadd(), and wchan_create().
int kprintf (const char * format, ...)
Referenced by allocpagerefpage(), arraytest(), arraytest2(), as_define_region(), attach_lnet_to_lamebus(), beep(), bitmaptest(), boot(), checkfilesystem(), cmd_bootfs(), cmd_chdir(), cmd_dispatch(), cmd_kheapdump(), cmd_mount(), cmd_prog(), cmd_progthread(), cmd_pwd(), cmd_shell(), cmd_testmenu(), cmd_unmount(), common_prog(), compute_thread(), config_lnet(), cpu_hatch(), cpu_identify(), createstress_thread(), cvtest(), cvtest2(), cvtestthread(), docreatestress(), dofstest(), dolongstress(), doreadstress(), dowritestress(), dowritestress2(), emu_close(), fail(), fstest_read(), fstest_remove(), fstest_write(), interprocessor_interrupt(), kgets(), kheap_dump(), kheap_dumpall(), kheap_printstats(), kill_curthread(), kmallocstress(), kmalloctest(), kmalloctest3(), kmalloctest4(), kmallocthread(), lamebus_interrupt(), lhd_code_to_errno(), load_elf(), load_segment(), locktest(), longstress_thread(), mainbus_bootstrap(), mainbus_reboot(), makewaiter(), menu(), menu_execute(), mips_trap(), nettest(), ok(), printfile(), ram_bootstrap(), readstress_thread(), runtest3(), semfs_getroot(), semtest(), semtestthread(), semu14(), semu15(), semu17(), semu19_sub(), semu2(), semu20(), semu21(), semu22(), semu3(), semu6(), sfs_domount(), sfs_getroot(), sfs_rename(), sfs_rwblock(), showmenu(), shutdown(), sleepalot_thread(), sleepthread(), subpage_kmalloc(), subpage_stats(), sys_reboot(), syscall(), thread_start_cpus(), threadlisttest(), threadtest(), threadtest2(), threadtest3(), translate_err(), tryattach_beep_to_ltimer(), tryattach_con_to_lser(), tryattach_emu_to_lamebus(), tryattach_lhd_to_lamebus(), tryattach_lrandom_to_lamebus(), tryattach_lser_to_lamebus(), tryattach_ltimer_to_lamebus(), tryattach_ltrace_to_lamebus(), tryattach_random_to_lrandom(), tryattach_rtclock_to_ltimer(), vfs_mount(), vfs_swapoff(), vfs_swapon(), vfs_unmount(), vfs_unmountall(), vm_fault(), vnode_check(), vnode_decref(), wakethread(), writestress2_thread(), and writestress_thread().
void kprintf_bootstrap (void)
Definition at line 65 of file kprintf.c.
References KASSERT, kprintf_spinlock, lock_create(), NULL, panic(), and spinlock_init().
Referenced by boot().
char* kstrdup (const char * str)
Definition at line 38 of file misc.c.
References kmalloc(), NULL, strcpy(), and strlen().
Referenced by cv_create(), fakethread_create(), lock_create(), proc_create(), sem_create(), semfs_direntry_create(), setup(), thread_create(), vfs_doadd(), and vfs_swapon().
void* memcpy (void * dest, const void * src, size_t len)
Definition at line 48 of file memcpy.c.
void* memmove (void * dest, const void * src, size_t len)
Definition at line 49 of file memmove.c.
void* memset (void * block, int ch, size_t len)
Definition at line 42 of file memset.c.
int __DEAD void panic (const char * format, ...)
Referenced by blocktype(), cmd_panic(), cpu_create(), cvtest(), cvtest2(), dev_create_vnode(), devnull_create(), docreatestress(), dolongstress(), doreadstress(), dowritestress(), dowritestress2(), emufs_reclaim(), fakethread_create(), hardclock_bootstrap(), init_sem(), init_threadsem(), inititems(), ipi_tlbshootdown(), kill_curthread(), kmallocstress(), kmalloctest3(), kmalloctest4(), kmalloctest4thread(), lamebus_attach_interrupt(), lamebus_detach_interrupt(), lamebus_init(), lamebus_interrupt(), lamebus_mark(), lamebus_unmark(), locktest(), lser_write(), mainbus_interrupt(), make_computes(), make_sleepalots(), makesem(), makewaiter(), menu_execute(), mips_trap(), proc_bootstrap(), randmax(), random(), runprogram(), runthreads(), semfs_bootstrap(), semtest(), semu1(), semu14(), semu15(), semu17(), semu19(), semu2(), semu20(), semu21(), semu22(), semu3(), semu5(), semu6(), sfs_balloc(), sfs_bmap(), sfs_bused(), sfs_dir_nentries(), sfs_gettype(), sfs_loadvnode(), sfs_lookonce(), sfs_reclaim(), sfs_rename(), sfs_rwblock(), spinlock_acquire(), strerror(), subpage_kfree(), sys_reboot(), thread_exit(), thread_switch(), translate_err(), uiomove(), vfs_bootstrap(), vm_fault(), vm_tlbshootdown(), and vnode_check().
void putch (int ch)
Definition at line 201 of file console.c.
References NULL, putch_delayed(), putch_intr(), putch_polled(), and the_console.
Referenced by backsp(), con_io(), console_send(), flush_delay_buf(), kgets(), loudthread(), and quietthread().
uint32_t randmax (void)
Definition at line 152 of file random.c.
References NULL, panic(), random_softc::rs_devdata, and random_softc::rs_randmax.
uint32_t random (void)
Definition at line 143 of file random.c.
int snprintf (char * buf, size_t maxlen, const char * fmt, ...)
Definition at line 148 of file snprintf.c.
References va_end, va_start, and vsnprintf().
Referenced by __bad_assert(), binname(), blockusagestr(), calcresult(), choose_name(), config_emu(), config_lhd(), cpu_create(), cpu_identify(), createstress_thread(), dotest(), dumpfileblock(), dumpfreemap(), dumpindirect(), dumpinode(), execvp(), fstest_makename(), killdir(), listdir(), longstress_thread(), main(), make_computes(), make_sleepalots(), mergedname(), openfiles(), pass1_dir(), pass1_direntry(), pass1_rootdir(), pass2(), pass2_dir(), prepdata(), recursedir(), recursive_cleanup(), runthreads(), semcreate(), semfs_sem_create(), setup(), test3(), try___getcwd(), try___time(), try_chdir(), try_close(), try_dup2(), try_execv(), try_fstat(), try_fsync(), try_ftruncate(), try_getdirentry(), try_ioctl(), try_link(), try_lseek(), try_lstat(), try_mkdir(), try_open(), try_pipe(), try_read(), try_readlink(), try_remove(), try_rename(), try_rmdir(), try_stat(), try_symlink(), try_waitpid(), try_write(), usem_init(), validname(), vfs_setbootfs(), vscomplain(), wait_siblings(), and writestress_thread().
char* strcat (char * dest, const char * src)
Definition at line 47 of file strcat.c.
char* strchr (const char * searched, int searchfor)
Definition at line 47 of file strchr.c.
int strcmp (const char * str1, const char * str2)
Definition at line 48 of file strcmp.c.
char* strcpy (char * dest, const char * src)
Definition at line 46 of file strcpy.c.
int const char* strerror (int errcode)
Definition at line 55 of file misc.c.
size_t strlen (const char * str)
Definition at line 47 of file strlen.c.
char* strrchr (const char * searched, int searchfor)
Definition at line 47 of file strrchr.c.
char* strtok_r (char * buf, const char * seps, char ** context)
Definition at line 50 of file strtok_r.c.
Variable Documentation
uint32_t dbflags
Definition at line 45 of file kprintf.c.