os161-doc: os161-base-2.0.2/kern/test/kmalloctest.c File Reference
kmalloctest.c File Reference
#include <types.h>
#include <kern/errno.h>
#include <lib.h>
#include <thread.h>
#include <synch.h>
#include <vm.h>
#include <test.h>
#include "opt-dumbvm.h"
Macros
#define NTRIES 1200
#define ITEMSIZE 997
#define NTHREADS 8
#define NUM_KM3_SIZES 5
#define NUM_KM4_SIZES 5
Functions
static void kmallocthread (void *sm, unsigned long num)
int kmalloctest (int nargs, char **args)
int kmallocstress (int nargs, char **args)
int kmalloctest3 (int nargs, char **args)
static void kmalloctest4thread (void *sm, unsigned long num)
int kmalloctest4 (int nargs, char **args)
Macro Definition Documentation
#define ITEMSIZE 997
Definition at line 58 of file kmalloctest.c.
Referenced by kmallocthread().
#define NTHREADS 8
Definition at line 59 of file kmalloctest.c.
Referenced by kmallocstress(), and kmalloctest4().
#define NTRIES 1200
Definition at line 57 of file kmalloctest.c.
Referenced by kmalloctest4thread(), and kmallocthread().
#define NUM_KM3_SIZES 5
Referenced by kmalloctest3().
#define NUM_KM4_SIZES 5
Referenced by kmalloctest4thread().
Function Documentation
int kmallocstress (int nargs, char ** args)
Definition at line 114 of file kmalloctest.c.
References kmallocthread(), kprintf(), NTHREADS, NULL, P(), panic(), sem_create(), sem_destroy(), strerror(), and thread_fork().
int kmalloctest (int nargs, char ** args)
Definition at line 101 of file kmalloctest.c.
References kmallocthread(), kprintf(), and NULL.
int kmalloctest3 (int nargs, char ** args)
Definition at line 173 of file kmalloctest.c.
References atoi(), DIVROUNDUP, EINVAL, KASSERT, kfree(), kmalloc(), kprintf(), NULL, NUM_KM3_SIZES, PAGE_SIZE, and panic().
int kmalloctest4 (int nargs, char ** args)
Definition at line 341 of file kmalloctest.c.
References kmalloctest4thread(), kprintf(), NTHREADS, NULL, P(), panic(), sem_create(), sem_destroy(), strerror(), and thread_fork().
static void kmalloctest4thread (void * sm, unsigned long num) static
Definition at line 300 of file kmalloctest.c.
References kfree(), kmalloc(), NTRIES, NULL, NUM_KM4_SIZES, PAGE_SIZE, panic(), and V().
Referenced by kmalloctest4().
static void kmallocthread (void * sm, unsigned long num) static
Definition at line 63 of file kmalloctest.c.
References ITEMSIZE, kfree(), kmalloc(), kprintf(), NTRIES, NULL, and V().
Referenced by kmallocstress(), and kmalloctest().