os161-doc: os161-base-2.0.2/kern/dev/lamebus/lscreen.c File Reference
lscreen.c File Reference
#include <types.h>
#include <lib.h>
#include <spinlock.h>
#include <platform/bus.h>
#include <lamebus/lscreen.h>
#include "autoconf.h"
Macros
#define LSCR_REG_POSN 0 /* Cursor position */
#define LSCR_REG_SIZE 4 /* Display size */
#define LSCR_REG_CHAR 8 /* Character in */
#define LSCR_REG_RIRQ 12 /* Read interrupt status */
#define LSCR_IRQ_ENABLE 1
#define LSCR_IRQ_ACTIVE 2
#define LSCR_SCREEN 32768
Functions
static void splitxy (uint32_t xy, unsigned *x, unsigned *y)
static uint32_t mergexy (unsigned x, unsigned y)
void lscreen_irq (void *vsc)
static void lscreen_newline (struct lscreen_softc *sc)
static void lscreen_char (struct lscreen_softc *sc, int ch)
void lscreen_write (void *vsc, int ch)
int config_lscreen (struct lscreen_softc *sc, int lscreenno)
Macro Definition Documentation
#define LSCR_IRQ_ACTIVE 2
Definition at line 51 of file lscreen.c.
Referenced by lscreen_irq().
#define LSCR_IRQ_ENABLE 1
Definition at line 50 of file lscreen.c.
Referenced by config_lscreen(), and lscreen_irq().
#define LSCR_REG_CHAR 8 /* Character in */
Definition at line 46 of file lscreen.c.
Referenced by lscreen_irq().
#define LSCR_REG_POSN 0 /* Cursor position */
Definition at line 44 of file lscreen.c.
Referenced by config_lscreen(), and lscreen_write().
#define LSCR_REG_RIRQ 12 /* Read interrupt status */
Definition at line 47 of file lscreen.c.
Referenced by config_lscreen(), and lscreen_irq().
#define LSCR_REG_SIZE 4 /* Display size */
Definition at line 45 of file lscreen.c.
Referenced by config_lscreen().
#define LSCR_SCREEN 32768
Definition at line 54 of file lscreen.c.
Referenced by config_lscreen().
Function Documentation
int config_lscreen (struct lscreen_softc * sc, int lscreenno)
Definition at line 188 of file lscreen.c.
References bus_map_area, bus_read_register, bus_write_register, lscreen_softc::ls_busdata, lscreen_softc::ls_buspos, lscreen_softc::ls_cx, lscreen_softc::ls_cy, lscreen_softc::ls_height, lscreen_softc::ls_lock, lscreen_softc::ls_screen, lscreen_softc::ls_width, LSCR_IRQ_ENABLE, LSCR_REG_POSN, LSCR_REG_RIRQ, LSCR_REG_SIZE, LSCR_SCREEN, spinlock_init(), and splitxy().
static void lscreen_char (struct lscreen_softc * sc, int ch) static
Definition at line 137 of file lscreen.c.
References ch, lscreen_softc::ls_cx, lscreen_softc::ls_cy, lscreen_softc::ls_screen, lscreen_softc::ls_width, and lscreen_newline().
Referenced by lscreen_write().
void lscreen_irq (void * vsc)
Definition at line 83 of file lscreen.c.
References bus_read_register, bus_write_register, ch, lscreen_softc::ls_busdata, lscreen_softc::ls_buspos, lscreen_softc::ls_devdata, lscreen_softc::ls_input, lscreen_softc::ls_lock, LSCR_IRQ_ACTIVE, LSCR_IRQ_ENABLE, LSCR_REG_CHAR, LSCR_REG_RIRQ, spinlock_acquire(), and spinlock_release().
Referenced by attach_lscreen_to_lamebus().
static void lscreen_newline (struct lscreen_softc * sc) static
Definition at line 114 of file lscreen.c.
References bzero(), lscreen_softc::ls_cx, lscreen_softc::ls_cy, lscreen_softc::ls_height, lscreen_softc::ls_screen, lscreen_softc::ls_width, and memmove().
Referenced by lscreen_char(), and lscreen_write().
void lscreen_write (void * vsc, int ch)
Definition at line 152 of file lscreen.c.
References bus_write_register, lscreen_softc::ls_busdata, lscreen_softc::ls_buspos, lscreen_softc::ls_cx, lscreen_softc::ls_cy, lscreen_softc::ls_lock, lscreen_softc::ls_width, LSCR_REG_POSN, lscreen_char(), lscreen_newline(), mergexy(), spinlock_acquire(), and spinlock_release().
Referenced by attach_con_to_lscreen().
static uint32_t mergexy (unsigned x, unsigned y) inline static
Definition at line 70 of file lscreen.c.
Referenced by lscreen_write().
static void splitxy (uint32_t xy, unsigned * x, unsigned * y) inline static
Definition at line 60 of file lscreen.c.
Referenced by config_lscreen().